services:
  postgres:
    image: postgres:16
    container_name: movie_checker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - movie_checker-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - movie-checker-net

  backend:
    build: ./backend
    container_name: movie_checker-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - movie-checker-net

  frontend:
    build: ./frontend
    container_name: movie_checker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - movie-checker-net

networks:
  movie-checker-net:
    driver: bridge

volumes:
  movie_checker-data:
