spring:
  application:
    name: movieChecker

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: movie_checker
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: movie_checker
    create-schemas: true
    default-schema: movie_checker
    baseline-on-migrate: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 1200       # 20m
    refreshTokenExpiration: 604800    # 7d
    resetTokenExpiration: 600         # 10m

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ACCOUNT}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

websiteBackendUrl: http://localhost:8080
websiteFrontendUrl: http://localhost:3000
