spring:
  application:
    name: movieChecker

  jpa:
    properties:
      hibernate:
        default_schema: movie_checker

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: movie_checker
    create-schemas: true
    default-schema: movie_checker
    baseline-on-migrate: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 1200       # 20m
    refreshTokenExpiration: 604800    # 7d
    resetTokenExpiration: 600         # 10m

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ACCOUNT}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

websiteBackendUrl: ${WEBSITE_BACKEND_URL:http://localhost:8080}
websiteFrontendUrl: ${WEBSITE_FRONTEND_URL:http://localhost:3000}
